[[mastodon.mappings]]
    account_name = "ChronosX"
    tg_channel_handle = "ChronosX_Channel"

[[mastodon.accounts]]
    name = "ChronosX"
    client_id = "abc"
    client_secret = "def"
    access_token = "ghi"
    api_base_url = "mstdn.netwhood.online"


[[mastodon.mappings]]
    account_name = "floppy"
    tg_channel_handle = "netwhood_news"

[[mastodon.accounts]]
    name = "floppy"
    client_id = "abc"
    client_secret = "def"
    access_token = "ghi"
    api_base_url = "mstdn.netwhood.online"

[telegram]
    api_id = "123123"
    api_hash = "qwerty"
    session_file = "/path/to/session/file"
    channels = ['netwhood_news', 'ChronosX_Channel']
